language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_install:
  - export "JAVA_HOME=/usr/lib/jvm/java-6-openjdk/"
before_script: 
  - sudo apt-get install antiword
  - sudo apt-get install poppler-utils
  - rake treat:install[travis] --trace
script: rake treat:spec