language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

before_install:
  - export "JAVA_HOME=/usr/lib/jvm/java-6-openjdk-i386/"

before_script:
  - sudo apt-get install antiword
  - sudo apt-get install poppler-utils
  - rake treat:install[travis] --trace

script: rake treat:spec --trace
